FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

ADD package*.json .
RUN npm install

COPY . .
COPY .env .

EXPOSE 4200
CMD ["npm", "run", "dev"]